// panel/dom.js — Centralised DOM references. Import `el` anywhere you need a DOM node.

'use strict';

const $ = (id) => document.getElementById(id);

export const el = {
  panelMain:          $('panel-main'),
  modelPill:          $('model-pill'),
  modelName:          $('model-name'),
  modelDropdown:      $('model-dropdown'),
  langPill:           $('lang-pill'),
  langName:           $('lang-name'),
  langDropdown:       $('lang-dropdown'),
  pseudoInput:        $('pseudo-input'),
  generateBtn:        $('generate-btn'),
  shortcutLabel:      $('shortcut-label'),
  errorMsg:           $('error-msg'),
  outputArea:         $('output-area'),
  outputCode:         $('output-code'),
  copyBtn:            $('copy-btn'),
  metricsCompact:     $('metrics-compact'),
  metricsToggle:      $('metrics-toggle'),
  metricsInfoBtn:     $('metrics-info-btn'),
  metricsExpanded:    $('metrics-expanded'),
  metricsInputTk:     $('metrics-input-tokens'),
  metricsThinkingRow: $('metrics-thinking-row'),
  metricsThinkingTk:  $('metrics-thinking-tokens'),
  metricsOutputTk:    $('metrics-output-tokens'),
  metricsTotalTk:     $('metrics-total-tokens'),
  metricsTotalCost:   $('metrics-total-cost'),
  sessionBanner:      $('session-banner'),
  sessionDot:         $('session-dot'),
  sessionStatusText:  $('session-status-text'),
  sessionMetricsText: $('session-metrics-text'),
  sessionCallCount:   $('session-call-count'),
  budgetBtn:          $('budget-btn'),
  budgetInput:        $('budget-input'),
  budgetBarWrap:      $('budget-bar-wrap'),
  budgetBarFill:      $('budget-bar-fill'),
  budgetBarLabel:     $('budget-bar-label'),
  lockBtn:            $('lock-btn'),
  sessionSummary:     $('session-summary'),
  efficiencyScore:    $('efficiency-score'),
  summaryIterations:  $('summary-iterations'),
  summaryTokens:      $('summary-tokens'),
  keysBtn:            $('keys-btn'),
  minimizeBtn:        $('minimize-btn'),
  wideBtn:            $('wide-btn'),
  wideIcon:           $('wide-icon'),
  historyBtn:         $('history-btn'),
  historyDrawer:      $('history-drawer'),
  historyList:        $('history-list'),
  historyCloseBtn:    $('history-close-btn'),
  clearHistoryBtn:    $('clear-history-btn'),
  infoModal:          $('info-modal'),
  infoModalClose:     $('info-modal-close'),
  syspromptBtn:       $('sysprompt-btn'),
  syspromptModal:     $('sysprompt-modal'),
  syspromptClose:     $('sysprompt-close'),
  githubBtn:          $('github-btn'),
};
